name: issue_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  tutorial_coach_mark: ^1.3.0 # For interactive onboarding tour
  pdf: ^3.11.0
  excel: ^4.0.6
  flutter_local_notifications: ^17.2.1
  lottie: ^3.1.2 # For animations
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # Added/Updated
  webview_flutter: ^4.0.5 # Added for in-app browser
  change_app_package_name: ^1.5.0 # Added for changing package name
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icon/ # Added
    - assets/images/developer_profile.jpg
    - android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png # Specific logo for About App
    - assets/animations/ # Added for Lottie animations

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"