// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.web:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appId: '1:488805180126:android:6ef23f323503e3bbc2d84f',
    apiKey: 'AIzaSyBTWgoSpwZpG7hdNha6qjK1yeFY3NGLOmM',
    projectId: 'issue-tracker-7cc5a',
    storageBucket: 'issue-tracker-7cc5a.firebasestorage.app',
    messagingSenderId: '488805180126',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    appId: '1:488805180126:ios:6ef23f323503e3bbc2d84f', // Placeholder, replace with actual iOS App ID if needed
    apiKey: 'AIzaSyBTWgoSpwZpG7hdNha6qjK1yeFY3NGLOmM', // Placeholder, replace with actual iOS API Key if needed
    projectId: 'issue-tracker-7cc5a',
    storageBucket: 'issue-tracker-7cc5a.firebasestorage.app',
    messagingSenderId: '488805180126',
  );
}
